```{r}
install.packages("caret")
install.packages("rpart.plot")
install.packages("rattle")
```

```{r}
# Load libraries
library(tidyverse)
library(tidymodels)
library(caret)
library(rpart)
library(rpart.plot)
library(rattle)
library(RColorBrewer)

# Read in the data
heart <- read.csv("heart_disease-1.csv")

```
```{r}
heart <- heart %>%
mutate(
    sex = factor(Sex),
    ChestPainType = factor(ChestPainType),
    RestingECG = factor(RestingECG),
    ExerciseAngina = factor(ExerciseAngina),
    ST_Slope = factor(ST_Slope),
    HeartDisease = factor(HeartDisease,
                          levels = c(0, 1),
                          labels = c("No", "Yes"))
)
```
```{r}
set.seed(12345)

heart_split <- initial_split(
  heart,
  prop = 0.70,
  strata = HeartDisease
)

heart_train <- training(heart_split)
heart_test  <- testing(heart_split)
```
```{r}
nrow(heart_train)

```

```{r}
tree_model <- rpart(
  HeartDisease ~ .,
  data = heart_train,
  method = "class"
)
```
```{r}
rpart.plot(tree_model, type = 3, extra = 104, fallen.leaves = TRUE)

```
```{r}
printcp(tree_model)

```

```{r}
set.seed(123)

folds <- vfold_cv(heart_train, v = 5, strata = HeartDisease)
```
```{r}
tree_spec <- decision_tree(
  cost_complexity = tune(),
  tree_depth = tune()
) %>%
  set_engine("rpart") %>%
  set_mode("classification")
```
```{r}
tree_recipe <- recipe(HeartDisease ~ ., data = heart_train)

```
```{r}
tree_workflow <- workflow() %>%
  add_model(tree_spec) %>%
  add_recipe(tree_recipe)

```
```{r}
tree_grid <- grid_regular(
  cost_complexity(),
  tree_depth(),
  levels = 5
)

```
```{r}
tree_tuned <- tune_grid(
  tree_workflow,
  resamples = folds,
  grid = tree_grid,
  metrics = metric_set(accuracy, roc_auc)
)

```
```{r}
tree_tuned %>%
  collect_metrics() %>%
  filter(.metric %in% c("accuracy", "roc_auc")) %>%
  ggplot(aes(cost_complexity, mean, color = .metric)) +
  geom_line() +
  geom_point() +
  scale_x_log10() +
  labs(x = "cp", y = "Performance")

```
```{r}
tree_tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  arrange(desc(mean))
```
```{r}
best_tree <- select_best(tree_tuned, metric = "accuracy")
final_workflow <- finalize_workflow(
  tree_workflow,
  best_tree
)
final_tree_fit <- fit(final_workflow, data = heart_train)
final_tree_fit %>% 
  extract_fit_engine() %>% # Extracts the actual rpart model
  rpart.plot(type = 3, extra = 104, fallen.leaves = TRUE)
```
```{r}
train_preds <- predict(final_tree_fit, heart_train) %>%
  bind_cols(heart_train)

accuracy(train_preds, truth = HeartDisease, estimate = .pred_class)

```
```{r}
sens(
  train_preds,
  truth = HeartDisease,
  estimate = .pred_class,
  event_level = "second"
)
```

```{r}
heart_train %>%
  count(HeartDisease) %>%
  mutate(prop = n / sum(n))

```
```{r}
test_preds <- predict(final_tree_fit, heart_test) %>%
  bind_cols(heart_test)

accuracy(
  test_preds,
  truth = HeartDisease,
  estimate = .pred_class
)

```

