```{r}
install.packages("gridExtra")
install.packages("vip")
```

```{r}
library(tidyverse)
library(tidymodels)
library(caret)
library(gridExtra)
library(vip)
library(ranger)

```
```{r}
drug <- read.csv("drug_data-2.csv", header = FALSE)
```

```{r}
names(drug) = c("ID", "Age", "Gender", "Education", "Country", "Ethnicity",
"Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive",
"SS", "Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis",
"Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh",
"LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA")
```

```{r}
drug[drug == "CL0"] = "No"
drug[drug == "CL1"] = "No"
drug[drug == "CL2"] = "Yes"
drug[drug == "CL3"] = "Yes"
drug[drug == "CL4"] = "Yes"
drug[drug == "CL5"] = "Yes"
drug[drug == "CL6"] = "Yes"
```

```{r}
library(dplyr)

drug_clean <- drug %>%
  # Convert Age through Ethnicity to factors first
  mutate(across(Age:Ethnicity, as.factor)) %>%
  
  # Fix Age labels (make sure number of labels = number of levels)
  mutate(Age = factor(Age,
                      levels = 1:7,  # match the actual numeric values in your Age column
                      labels = c("18_24","25_34","35_44","45_54","55_64","65_74","75_"))) %>%
  
  # Fix Gender (make sure levels match original data, e.g., 1 = Male, 2 = Female)
  mutate(Gender = factor(Gender, levels = 1:2, labels = c("Male","Female"))) %>%
  
  # Education (make sure levels = 1:9)
  mutate(Education = factor(Education, levels = 1:9,
                            labels = c("Under16","At16","At17","At18",
                                       "SomeCollege","ProfessionalCert",
                                       "Bachelors","Masters","Doctorate"))) %>%
  
  # Country (levels = 1:7)
  mutate(Country = factor(Country, levels = 1:7,
                          labels = c("USA","NewZealand","Other","Australia",
                                     "Ireland","Canada","UK"))) %>%
  
  # Ethnicity (levels = 1:7)
  mutate(Ethnicity = factor(Ethnicity, levels = 1:7,
                            labels = c("Black","Asian","White",
                                       "White/Black","Other",
                                       "White/Asian","Black/Asian"))) %>%
  
  # Convert drug columns to factors
  mutate(across(Alcohol:VSA, as.factor)) %>%
  
  # Remove ID
  select(-ID)
```

```{r}
str(drug_clean)
```

```{r}
drug_clean = drug_clean %>% select(!(Alcohol:Mushrooms)) %>% select(!(Semer:VSA))
```

```{r}
anyNA(drug_clean)
```

```{r}
set.seed(1234)

drug_split <- initial_split(
  drug_clean,
  prop = 0.70,
  strata = Nicotine
)

drug_train <- training(drug_split)
drug_test  <- testing(drug_split)

nrow(drug_train)

```

```{r}
p1 <- ggplot(drug_clean, aes(Age, fill = Nicotine)) +
  geom_bar(position = "fill") +
  labs(y = "Proportion")

p2 <- ggplot(drug_clean, aes(Gender, fill = Nicotine)) +
  geom_bar(position = "fill")

p3 <- ggplot(drug_clean, aes(Education, fill = Nicotine)) +
  geom_bar(position = "fill") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p4 <- ggplot(drug_clean, aes(Country, fill = Nicotine)) +
  geom_bar(position = "fill")

```

```{r}
grid.arrange(p1, p2, p3, p4, ncol = 2)

```

```{r}
ggplot(drug_clean, aes(Impulsive, fill = Nicotine)) +
  geom_density(alpha = 0.5)

```

```{r}
set.seed(123)

folds <- vfold_cv(drug_train, v = 5, strata = Nicotine)

```
```{r}
rf_spec <- rand_forest(
  mtry = tune(),
  min_n = tune(),
  trees = 100
) %>%
  set_engine("ranger", importance = "impurity") %>%
  set_mode("classification")

rf_recipe <- recipe(Nicotine ~ ., data = drug_train)
rf_workflow <- workflow() %>%
  add_model(rf_spec) %>%
  add_recipe(rf_recipe)

rf_grid <- grid_regular(
  mtry(range = c(2, 8)),
  min_n(range = c(5, 20)),
  levels = 10
)

```
```{r}
set.seed(123)

rf_tuned <- tune_grid(
  rf_workflow,
  resamples = folds,
  grid = rf_grid,
  metrics = metric_set(accuracy)
)

rf_tuned %>%
  collect_metrics() %>%
  ggplot(aes(mtry, mean, color = factor(min_n))) +
  geom_line() +
  geom_point()

```

```{r}
best_rf <- select_best(rf_tuned, metric = "accuracy")

final_rf_workflow <- finalize_workflow(
  rf_workflow,
  best_rf
)

final_rf_fit <- fit(final_rf_workflow, data = drug_train)

```

```{r}
final_rf_fit %>%
  extract_fit_parsnip() %>%
  vip(num_features = 10)

```

```{r}
train_preds <- predict(final_rf_fit, drug_train) %>%
  bind_cols(drug_train)

accuracy(train_preds, truth = Nicotine, estimate = .pred_class)

```

```{r}
drug_train %>%
  count(Nicotine) %>%
  mutate(prop = n / sum(n))

```

```{r}
test_preds <- predict(final_rf_fit, drug_test) %>%
  bind_cols(drug_test)

accuracy(test_preds, truth = Nicotine, estimate = .pred_class)

```

